{% raw %}
{{- range $env_name, $overrides := (get .Values .Values.environment_name).envs }}
{{- with $ }}
{{- with (set . "Values" (mustMergeOverwrite .Values  ($overrides|default dict) (dict "env_name" $env_name))) }}
{{- if .Values.enabled }}
{{- if .Values.hpa.enabled }}
---
{{- $fullName := include "funda-helper.fullname" . -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "funda-helper.fullname" . }}
  labels:
    app: {{ template "funda-helper.name" . }}
    chart: {{ template "funda-helper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ template "funda-helper.chart" . }}
spec:
  scaleTargetRef:
    apiVersion: {{ .Values.hpa.apiVersion }}
    kind: {{ .Values.hpa.kind }}
    name: {{ template "funda-helper.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
{{- with .Values.hpa.metrics }}
{{ toYaml . | indent 2 }}
{{- end }}
  behavior:
{{- with .Values.hpa.behavior }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{% endraw %}