trigger:
  paths:
    exclude:
    - docs/*
    - azure-pipelines-docs.yml

resources:
  repositories:
    - repository: templates
      type: github
      name: fundarealestate/funda-azdo-templates
      endpoint: fundarealestate

pool:
  vmImage: ubuntu-latest

stages:
- template: nuget-package/build-publish-dotnet.yaml@templates
  parameters: 
    defaultBranchName : master
