{% raw %}
{{/* Merge {cluster}.envs.{subEnv} dict into .Values */}}
{{- range $env_name, $env_overrides := ((get .Values .Values.environment_name).envs) }}
{{- with mustDeepCopy $ }}
{{- $_ := set . "Values" (mustMergeOverwrite .Values ($env_overrides | default dict) (dict "env_name" $env_name)) }}

{{- if .Values.enabled }}

{{/* Merge {cluster}.envs.{subEnv}.services.{serviceName} dict into .Values */}}
{{ $root := . }}
{{- range $service_name, $service_overrides := .Values.services }}
{{- with mustDeepCopy $root }}
{{- $_ := set . "Values" (mustMergeOverwrite .Values ($service_overrides | default dict) (dict "service_name" $service_name)) }}

{{- if .Values.serviceAccount.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "funda-helper.serviceAccountName" . }}
  labels:
    app: {{ template "funda-helper.name" . }}
    chart: {{ template "funda-helper.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Values.image.tag | quote }}
    helm.sh/chart: {{ template "funda-helper.chart" . }}

{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{% endraw %}