parameters:
  - name: environment
    type: string
  - name: imageTag
    type: string

resources:
  repositories:
    - repository: templates
      type: github
      ref: 0.2
      name: fundarealestate/service-pipeline-templates
      endpoint: fundarealestate
  
stages:

  - template: service/deploy/terraform-plan-apply.yml@templates
    parameters:
      name: TerraformPlanApply
      environment: {% raw %} ${{ parameters.environment }} {% endraw %}
      stateKey: ${{ values.applicationName | lower }}

  - template: service/deploy/push-helm.yml@templates
    parameters:
      name: PushHelm
      dependsOn: UpgradeTasks
      releaseName: ${{ values.applicationName | lower }}
      environment: {% raw %} ${{ parameters.environment }} {% endraw %}
      imageTag: {% raw %} ${{ parameters.imageTag}} {% endraw %}