# This is a placeholder until the service pipeline templates can be integrated
trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - '*'

resources:
  repositories:
    - repository: templates
      type: github
      ref: refs/tags/0.4.1
      name: fundarealestate/service-pipeline-templates
      endpoint: fundarealestate

stages:
  - template: service/build/build.yml@templates
    parameters:
      buildProjects:
        - projectName: ${{ values.dirNamePrefix }}
          imageName: ${{ values.name | lower }}

  - template: service/build/unit-tests-dotnet.yml@templates
    parameters:
      dependsOn: Build

  - template: service/build/validate-terraform.yml@templates
    parameters:
      dependsOn: UnitTests