parameters:
  - name: environment
    type: string
  - name: imageTag
    type: string
  - name: stateKey
    type: string
  - name: releaseName
    type: string 


resources:
  repositories:
    - repository: templates
      type: github
      ref: 0.2
      name: fundarealestate/service-pipeline-templates
      endpoint: fundarealestate
  
stages:

  - template: service/deploy/terraform-plan-apply.yml@templates
    parameters:
      name: TerraformPlanApply
      notifyUsers: my-team@funda.nl # Use your own team's email address
      environment: ${{ parameters.environment }}
      stateKey: ${{ parameters.stateKey }}

  - template: service/deploy/push-helm.yml@templates
    parameters:
      name: PushHelm
      dependsOn: UpgradeTasks
      releaseName: ${{ parameters.releaseName }}
      environment: ${{ parameters.environment }}
      imageTag: ${{ parameters.imageTag}}
      
